### NUMPY

S'utilitza per a la computació estadística, científica etc de forma eficient.
proporcionarà Arrays, eines matemàtiques, combinació amb altres softwares mes ràpids (C, fortran...)

In [1]:
import numpy as np

In [2]:
#array de zeros
a = np.zeros((2,4))#2 files i 4 columnes

In [3]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

aquest array te 2 **axis** doncs te longitud 2 i el segon de longitud 4
un **rank** de 2
un **shape** de (2,4)
i un **size** de 8

In [4]:
#array de 1
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
#omplim el array amb un valor
np.full((2,3,4),8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [7]:
#els valors es posen per defecte amb els valors que hi hagi al disc de memòria
np.empty((2,3,9))

array([[[ 9.40435994e-312,  9.40398669e-312,  3.74168656e+233,
          1.23769245e+224,  1.97937692e+161,  1.05948155e-153,
          4.47435561e-067,  4.61101792e+252,  2.20892696e+161],
        [ 7.08468655e+159,  9.45007090e-076,  1.15297798e-259,
          6.01347002e-154,  1.05089607e-153,  2.42766135e-154,
          2.93573416e+222,  3.36749394e+257,  1.02809935e+213],
        [ 9.41072606e-095,  1.03478485e-013,  1.05161974e-153,
          6.32300944e+233,  2.43905762e-154,  4.83245960e+276,
          5.56206154e+180,  8.03408340e-095,  5.50495710e-095]],

       [[ 6.01347002e-154,  1.16310967e+214,  5.50409548e+257,
          5.03734573e+180,  6.01347002e-154,  8.59641098e+030,
          3.88834045e+160,  5.36788256e+242,  2.42766135e-154],
        [ 2.93573416e+222,  3.36749394e+257,  1.02809935e+213,
          9.41072606e-095,  1.01159728e-153,  1.96567740e-062,
          4.27255707e+180,  5.98147555e-154,  1.03063392e-113],
        [ 1.05132387e-153,  6.01346953e-154,  8.

In [14]:
#incialitzar array utilitzant una llista de python
b = np.array([[1,2,3],[4,5,6]])

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b.shape

(2, 3)

In [18]:
b.ndim

2

In [19]:
#creació de l'array utilitzant una funció basada en rangs
#(mínim, màxim, numer de elements)
print(np.linspace(0,6,10))

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


In [20]:
#valors aleatoris
np.random.rand(2,3,4)

array([[[0.75803734, 0.92507111, 0.765491  , 0.09311133],
        [0.0761894 , 0.71031726, 0.38194959, 0.19281494],
        [0.80965415, 0.03487771, 0.65322284, 0.85170304]],

       [[0.67735517, 0.91876355, 0.63096561, 0.45999276],
        [0.67627918, 0.94711611, 0.53229688, 0.01355284],
        [0.40443083, 0.61138251, 0.22929005, 0.08052038]]])

In [22]:
#inicialitzem aleatoris en base a distribucions per exemple la normal
np.random.randn(2,4)

array([[-0.56573558, -2.13322583, -0.93662459,  0.12408527],
       [ 0.75844406, -0.34577222, -0.08130197,  1.26044897]])

## Acces als arrays


In [25]:
array_uni = np.array([1,3,5,7,9,11])
print(array_uni.shape)
print(array_uni)

(6,)
[ 1  3  5  7  9 11]


In [26]:
#accedim als elements
array_uni[4]

9

In [27]:
array_uni[2:4]

array([5, 7])

In [28]:
#stripe (agafa del zero fins el final saltant de 3 en 3)
array_uni[0::3]

array([1, 7])

In [30]:
array_multi = np.array([[1,2,3,4],[5,6,7,8]])
print(array_multi.shape)
array_multi

(2, 4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
array_multi[0,3]

4

In [33]:
#accedim a la segona fila del array
array_multi[1,:]

array([5, 6, 7, 8])

In [36]:
# accedim al tercer element de les dues primeres files (De la fila 0 a la 2, agafa el index 2)
array_multi[0:2,2] 

array([3, 7])

# modificació d'un array


In [39]:
# creació d'un array del 0 al 27

array1 = np.arange(28)
array1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [41]:
# Cambiem les dimensions
array1.shape = (7,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [46]:
#Ara modifiquem l'array
array2 = array1.reshape(4,7)
array2


array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [47]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [48]:
array2[0,3] = 20

In [49]:
array2

array([[ 0,  1,  2, 20,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [50]:
array1

array([[ 0,  1,  2, 20],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [51]:
# revelem el array original
array1.ravel()

array([ 0,  1,  2, 20,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [52]:
#Operacions amb arrays



In [53]:
array1 = np.arange(2,18,2)

In [54]:
array2 = np.arange(8)

In [55]:
array1

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [56]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [57]:
#suma 
array1 + array2

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [58]:
#resta
array1 - array2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
#multiplicació 

In [60]:
array1 * array2

array([  0,   4,  12,  24,  40,  60,  84, 112])

# BROADCASTING

In [61]:
array1 = np.arange(5)

In [63]:
array2 = np.array([3])

In [64]:
array1

array([0, 1, 2, 3, 4])

In [65]:
array2

array([3])

In [67]:
array1 + array2

array([3, 4, 5, 6, 7])

# funcions estadistiques

In [68]:
array1 = np.arange(1,20,2)

In [69]:
array1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [70]:
#mitjana

In [71]:
array1.mean()

10.0

In [72]:
#Suma de tots els elements
array1.sum()

100

In [73]:
# opcions
dir(array1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

# Universal functions

In [74]:
#cuadrado
np.square(array1)

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [77]:
#arrel
np.sqrt(array1)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])